# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "task-1"
    # Customize the amount of memory on the VM:
    vb.memory = "512"
  end

  # Install apache2
  config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y apache2 php libapache2-mod-php
        sudo echo 'Listen 8081' >> /etc/apache2/ports.conf
        sudo systemctl enable apache2
        sudo systemctl restart apache2
  SHELL

  # Config apache2
  config.vm.provision "file", source: "index.html", destination: "/tmp/index.html"
  config.vm.provision "file", source: "index.php", destination: "/tmp/index.php"
  config.vm.provision "file", source: "php-site.conf", destination: "/tmp/php-site.conf"
  config.vm.provision "shell", inline: <<-SHELL
        sudo mkdir /var/www/html/php/
        sudo mv /tmp/index.html /var/www/html/
        sudo mv /tmp/index.php /var/www/html/php/
        sudo mv /tmp/php-site.conf /etc/apache2/sites-available/

        sudo a2ensite php-site.conf
        sudo systemctl restart apache2
  SHELL
end