jenkins_home: /var/lib/jenkins
jenkins_file_path: /vagrant/roles/jenkins/files/
jenkins_scripts_path: /vagrant/roles/jenkins/files/scripts/*
jenkins_repo_url: https://pkg.jenkins.io/debian-stable binary/
jenkins_key_url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
jenkins_plugin_manager_url: https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.12.13/jenkins-plugin-manager-2.12.13.jar
