---
version: '3.3'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    networks:
      - local
    ports:
      - "8080:8080"
    depends_on:
      - nexus
  nexus:
    build:
      context: .
      dockerfile: Dockerfile.nexus
      args:
        - nexus_wcg_username=nexus-wcg
        - nexus_wcg_password=nexus-wcg
    networks:
      - local
    ports:
      - "8081:8081"
    healthcheck:
      test: curl -f http://localhost:8081||exit 1
      interval: 20s
      timeout: 10s
      retries: 3
networks:
  local: {}