FROM debian

RUN apt-get update && \
    apt-get install -y vim mc ansible sshpass git gnupg rsync bash && \
    apt-get clean

COPY /nexus-files/playbook-nexus.yaml /vagrant/playbook-nexus.yaml
COPY /nexus-files/requirements.yml /vagrant/requirements.yml
COPY /nexus-files/inventory /vagrant/inventory

WORKDIR /vagrant/

RUN ansible-galaxy install -r requirements.yml
RUN ansible-playbook -i inventory playbook-nexus.yaml

EXPOSE 8081

CMD ["sh", "-c", "/opt/nexus-latest/bin/nexus run"]