---
- name: Ansible master config
  hosts: master
  become: true

  tasks:
    - file:
        path: '{{ item.fpath }}'
        state: file
        owner: vagrant
        mode: u+rw,g-rwx,o-rwx
      loop:
        - { fpath: /home/vagrant/private_key_slave1 }
        - { fpath: /home/vagrant/private_key_slave2 }

    - name: Install Puppet
      yum:
        update_cache: yes
        name: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
        state: present
        disable_gpg_check: yes

    - name: Install packages
      yum:
        name:
          - puppetserver
          - vim
          - git
        state: present
        update_cache: yes

    - name: Copy puppetserver config
      copy:
        src: puppetserver
        dest: /etc/sysconfig/puppetserver

    - name: Added master to hosts
      lineinfile:
        path: /etc/hosts
        line: '127.0.1.1 puppet'

    - name: Disable firewalld
      service:
        name: firewalld
        enabled: false
        state: stopped

    - name: Copy autosign.conf
      copy:
        src: autosign.conf
        dest: /etc/puppetlabs/puppet/autosign.conf

    - name: Install r10k
      shell: /opt/puppetlabs/puppet/bin/gem install r10k

    - name: Creates directory for r10k
      file:
        path: /etc/puppetlabs/r10k
        state: directory

    - name: Copy r10k.yaml
      copy:
        src: r10k.yaml
        dest: /etc/puppetlabs/r10k/r10k.yaml

    - name: Start puppetserver
      systemd:
        name: puppetserver.service
        enabled: true
        state: started

    - name: Add r10k cron job
      cron:
        name: "r10k deploy"
        minute: "1"
        job: "/opt/puppetlabs/puppet/bin/r10k deploy environment -p"

- name: Ansible slave config
  hosts:
    - slave1
    - slave2
  become: true

  tasks:
    - name: Install Puppet
      yum:
        update_cache: yes
        name: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
        state: present
        disable_gpg_check: yes

    - name: Copy index.html
      copy:
        src: index.html
        dest: /tmp/index.html

    - name: Copy selinux config
      copy:
        src: config
        dest: /etc/selinux/config

    - name: Copy index.php
      copy:
        src: index.php
        dest: /tmp/index.php

    - name: Install packages
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - vim
        - mc
        - puppet-agent

    - name: Added master to hosts
      lineinfile:
        path: /etc/hosts
        line: '192.168.50.4 master.puppet puppet'

    - name: Add agent in config
      blockinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        block: |
          [agent]
          server = master.puppet
          runinterval = 1m
          environment = production
      notify:
        - Start puppet-agent

  handlers:
    - name: Start puppet-agent
      service:
        name: puppet
        state: started
        enabled: yes
