# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8s"
  config.vm.synced_folder ".", "/vagrant", disabled: false

  config.vm.define "slave1" do |slave1|
    slave1.vm.network "private_network", ip: "192.168.50.5"
    slave1.vm.hostname = "slave1.puppet"

    slave1.vm.provider "virtualbox" do |vb|
      vb.name = "task-1-slave1"
      vb.memory = "512"
    end

    slave1.vm.provision :shell, inline: <<-SHELL
            yum install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
    SHELL

    slave1.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yaml"
    end
  end

  config.vm.define "slave2" do |slave2|
    slave2.vm.network "private_network", ip: "192.168.50.6"
    slave2.vm.hostname = "slave2.puppet"

    slave2.vm.provider "virtualbox" do |vb|
      vb.name = "task-1-slave2"
      vb.memory = "512"
    end

    slave2.vm.provision :shell, inline: <<-SHELL
            yum install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
    SHELL

    slave2.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yaml"
    end
  end

  config.vm.define "master", primary: true do |master|
    master.vm.network "private_network", ip: "192.168.50.4"
    master.vm.hostname = "master.puppet"

    master.vm.provider "virtualbox" do |vb|
      vb.name = "task-1-master"
      vb.memory = "1024"
    end

    master.vm.provision :shell, inline: <<-SHELL
            yum install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
    SHELL

    master.vm.provision "ansible_local" do |ansible|
      ansible.limit = 'all'
      ansible.inventory_path = "inventory"
      ansible.playbook = "playbook.yaml"
    end
  end
end