FROM golang:1.16 AS builder
WORKDIR /app
RUN git clone https://github.com/Fenikks/word-cloud-generator.git
WORKDIR /app/word-cloud-generator
RUN make

FROM alpine:latest
RUN apk add --no-cache libc6-compat
COPY --from=builder /app/word-cloud-generator/artifacts/linux/word-cloud-generator /usr/local/bin/
CMD ["word-cloud-generator"]