FROM golang:1.16 AS builder
WORKDIR /app
RUN git clone https://github.com/Fenikks/word-cloud-generator.git
WORKDIR /app/word-cloud-generator
RUN make build

FROM alpine:latest
COPY --from=builder /app/word-cloud-generator/word-cloud-generator /usr/local/bin/
CMD ["word-cloud-generator"]