unclassified:
  locale:
    systemLocale: en
    ignoreAcceptLanguage: true

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope:    GLOBAL
              id:       nexus-creds-admin
              username: nexus-admin
              password: nexus-admin
              description: "nexus_creds_admin"
          - usernamePassword:
              scope:    GLOBAL
              id:       nexus-creds
              username: nexus-wcg
              password: nexus-wcg
              description: "nexus_creds_wcg"

tool:
  go:
    installations:
      - name: "go-1.16"
        properties:
          - installSource:
              installers:
                - golangInstaller:
                    id: "1.16"