---
- name: Ansible master config
  hosts: master
  become: true

  tasks:
    - file:
        path: '{{ item.fpath }}'
        state: file
        owner: vagrant
        mode: u+rw,g-rwx,o-rwx
      loop:
        - { fpath: /home/vagrant/private_key_slave1 }
        - { fpath: /home/vagrant/private_key_slave2 }
        - { fpath: /home/vagrant/private_key_mineserver }

    - name: Install Puppet
      yum:
        update_cache: yes
        name: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
        state: present
        disable_gpg_check: yes

    - name: Install packages
      yum:
        name:
          - puppetserver
          - vim
          - git
        state: present
        update_cache: yes

    - name: Set memory limit for Puppet Server
      lineinfile:
        path: /etc/sysconfig/puppetserver
        regexp: '^JAVA_ARGS='
        line: 'JAVA_ARGS="-Xms512m -Xmx512m -Djruby.logger.class=com.puppetlabs.jruby_utils.jruby.Slf4jLogger"'

    - name: Added master to hosts
      lineinfile:
        path: /etc/hosts
        line: '127.0.1.1 puppet'

    - name: Add port 8140 to firewalld
      firewalld:
        port: 8140/tcp
        permanent: yes
        state: enabled

    - name: Copy autosign.conf
      copy:
        src: autosign.conf
        dest: /etc/puppetlabs/puppet/autosign.conf

    - name: Add agent in config
      blockinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        block: |
          [agent]
          server = master.puppet
          runinterval = 1m
          environment = production
      notify:
        - Start puppet-agent

    - name: Install r10k
      shell: /opt/puppetlabs/puppet/bin/gem install r10k

    - name: Creates directory for r10k
      file:
        path: /etc/puppetlabs/r10k
        state: directory

    - name: Copy r10k.yaml
      copy:
        src: r10k.yaml
        dest: /etc/puppetlabs/r10k/r10k.yaml

    - name: Start puppetserver
      systemd:
        name: puppetserver.service
        enabled: true
        state: started

    - name: Get r10k modules
      command: /opt/puppetlabs/puppet/bin/r10k deploy environment -p

    - name: Add r10k cron job
      cron:
        name: "r10k deploy"
        minute: "*"
        hour: "*"
        user: root
        job: "/opt/puppetlabs/puppet/bin/r10k deploy environment -p"

  handlers:
    - name: Start puppet-agent
      service:
        name: puppet
        state: started
        enabled: yes

- name: Ansible slave/mineserver config
  hosts:
    - slave1
    - slave2
    - mineserver
  become: true

  tasks:
    - name: Install Puppet repository
      yum:
        update_cache: yes
        name: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
        state: present
        disable_gpg_check: yes

    - name: Copy selinux config
      copy:
        src: config
        dest: /etc/selinux/config

    - name: Install packages
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - vim
        - puppet-agent

    - name: Added master to hosts
      lineinfile:
        path: /etc/hosts
        line: '192.168.50.4 master.puppet puppet'

    - name: Add agent in config
      blockinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        block: |
          [agent]
          server = master.puppet
          runinterval = 1m
          environment = production
      notify:
        - Start puppet-agent

  handlers:
    - name: Start puppet-agent
      service:
        name: puppet
        state: started
        enabled: yes
