# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.define "slave1" do |slave1|
    slave1.vm.box = "generic/debian11"
    slave1.vm.synced_folder ".", "/vagrant", disabled: false
    slave1.vm.network "private_network", ip: "192.168.50.5"

    slave1.vm.provider "virtualbox" do |vb|
      vb.name = "task-2-slave1"
      vb.memory = "1024"
    end

    slave1.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook-slave1.yaml"
    end
  end

  config.vm.define "slave2" do |slave2|
    slave2.vm.box = "generic/debian11"
    slave2.vm.synced_folder ".", "/vagrant", disabled: false
    slave2.vm.network "private_network", ip: "192.168.50.6"

    slave2.vm.provider "virtualbox" do |vb|
      vb.name = "task-2-slave2"
      vb.memory = "1024"
    end

    slave2.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook-slave2.yaml"
    end
  end

  config.vm.define "master", primary: true do |master|
    master.vm.box = "generic/debian11"
    master.vm.network "forwarded_port", guest: 80, host: 8080
    master.vm.network "forwarded_port", guest: 8080, host: 8080
    master.vm.network "forwarded_port", guest: 8081, host: 8081
    master.vm.synced_folder ".", "/vagrant", disabled: false
    master.vm.network "private_network", ip: "192.168.50.4"

    master.vm.provider "virtualbox" do |vb|
      vb.name = "task-2-master"
      vb.memory = "1024"
    end

    master.vm.provision "ansible_local" do |ansible|
      ansible.limit = 'all'
      ansible.inventory_path = "inventory"
      ansible.playbook = "playbook-master.yaml"
    end
  end
end