Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/vagrant", disabled: false
    #config.vm.network "private_network", ip: "192.168.33.33"
  
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus   = 2
    end
  
    config.vm.provision "shell", privileged: false, inline: <<-SHELL
        mkdir actions-runner && cd actions-runner    
        curl -o actions-runner-linux-x64-2.299.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.306.0/actions-runner-linux-x64-2.306.0.tar.gz
        tar xzf ./actions-runner-linux-x64-2.306.0.tar.gz
    SHELL

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y ca-certificates curl gnupg lsb-release zip
        
        curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        apt-get install -y docker-ce docker-ce-cli containerd.io
        usermod -aG docker vagrant
        
        sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
        sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
        sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /root/.bashrc

        rm /usr/bin/python
        cd /usr/bin
        ln -s python3 python
        apt-get install -y python3-pip
        ln -s pip3 pip
    SHELL
end