unclassified:
  locale:
    systemLocale: en
    ignoreAcceptLanguage: true

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope:    GLOBAL
              id:       staging_creds
              username: vagrant
              password: vagrant
              description: "staging_creds"
          - usernamePassword:
              scope:    GLOBAL
              id:       production_creds
              username: vagrant
              password: vagrant
              description: "production_creds"
          - usernamePassword:
              scope:    GLOBAL
              id:       nexus_creds_admin
              username: nexus-admin
              password: nexus-admin
              description: "nexus_creds_admin"
          - usernamePassword:
              scope:    GLOBAL
              id:       nexus_creds_wcg
              username: nexus-wcg
              password: nexus-wcg
              description: "nexus_creds_wcg"

tool:
  go:
    installations:
      - name: "go_lang"
        properties:
          - installSource:
              installers:
                - golangInstaller:
                    id: "1.16"