---
- name: Nexus config
  hosts: nexus
  become: true
  roles:
    - geerlingguy.nexus3-oss

  pre_tasks:
    - name: Add key
      apt_key:
        url: https://download.bell-sw.com/pki/GPG-KEY-bellsoft

    - name: Add repository
      apt_repository:
        repo: deb [arch=amd64] https://apt.bell-sw.com/ stable main
        state: present
        update_cache: true

    - name: Install Java
      apt:
        name: bellsoft-java8-full
        state: present

  vars:
    nexus_admin_password: "admin"
    nexus_delete_default_repos: true
    nexus_config_raw: true

    nexus_repos_raw_hosted:
      - name: wcg-repo
        blob_store: default

    nexus_roles:
      - id: nx-uploader
        name: nx-uploader
        description: Role nx-uploader for word-cloud-generator
        privileges:
          - nx-repository-view-raw-wcg-repo-*
        roles: []

    nexus_local_users:
      - username: "{{ wcg_username }}"
        password: "{{ wcg_password }}"
        first_name: Jenkins
        last_name: CI
        email: support@company.com
        roles:
          - nx-uploader