unclassified:
  locale:
    systemLocale: en
    ignoreAcceptLanguage: true

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope:    GLOBAL
              id:       slave_creds
              username: vagrant
              password: vagrant
              description: "slave_creds"
          - usernamePassword:
              scope:    GLOBAL
              id:       nexus_creds
              username: nexus
              password: nexus
              description: "nexus_creds"

tool:
  go:
    installations:
      - name: "go_lang"
        properties:
          - installSource:
              installers:
                - golangInstaller:
                    id: "1.16"