apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploy.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ .Values.container.label.key }}: {{ .Values.container.label.value }}
  template:
    metadata:
      labels:
        {{ .Values.container.label.key }}: {{ .Values.container.label.value }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.container.port }}