name: WCG CI

on:
  push:
    branches:
      - master
    paths:
      - '07-docker/**'
      - '12-helm/**'
  workflow_dispatch:

env:
  IMAGE_NAME: wcg
  REPO_OWNER: ${{ github.repository_owner }}
  DOCKER_TAG: ${{ github.sha }}
  GITHUB_PAGES_URL: https://skvorchevski.github.io/devops-hometasks/

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Test helm chart
        run: helm lint 12-helm/

      - name: Helm package
        run: helm package 12-helm/ --version ${{ steps.tag_version.outputs.new_tag }} --app-version ${{ steps.tag_version.outputs.new_tag }} -d charts

      - name: Update help index.yaml
        run: helm repo index /charts --url ${{ env.GITHUB_PAGES_URL }} .

      - name: Commit helm package
        uses: stefanzweifel/git-auto-commit-action@v4

      - name: Add new git repository_owner
        run: echo "REPO_OWNER_LC=${REPO_OWNER,,}" >>${GITHUB_ENV}

      - name: Print env
        run: echo "github_actor:=${{ github.actor }} repo_owner:= $REPO_OWNER repo_owner_lc:= $REPO_OWNER_LC  docker_tag:= $DOCKER_TAG"

      - name: Get Word-Cloud-Generator
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./07-docker
          file: ./07-docker/Dockerfile.multi
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.REPO_OWNER_LC }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}
            ghcr.io/${{ env.REPO_OWNER_LC }}/${{ env.IMAGE_NAME }}:${{ steps.tag_version.outputs.new_tag }}